
export const REQUEST_CONTACTS = 'REQUEST_CONTACTS::Contacts';
export const REQUEST_CONTACTS_SUCCESS = 'REQUEST_CONTACTS_SUCCESS::Contacts';
export const REQUEST_CONTACTS_ERROR = 'REQUEST_CONTACTS_ERROR::Contacts';

export const EDIT_CONTACT = 'EDIT_CONTACT::Contacts';
export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS::Contacts';
export const EDIT_CONTACT_ERROR = 'EDIT_CONTACT_ERROR:Contacts';


//TOTO rename
export const REQUEST_CONTACT_BY_ID = 'REQUEST_CONTACT_BY_ID::Contacts';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS::Contacts';
export const GET_CONTACT_ERROR = 'GET_CONTACT_ERROR::Contacts';

export const DELETE_CONTACT_BY_ID = 'DELETE_CONTACT_BY_ID::Contacts';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS::Contacts';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR::Contacts'; 

export const CREATE_CONTACT = 'CREATE_CONTACT::Contacts';
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS::Contacts';
export const CREATE_CONTACT_ERROR = 'CREATE_CONTACT_ERROR::Contacts';

export const SELECT_EMPTY = 'SELECT_EMPTY::Contacts';

